Improve error handling and robustness of cloud component access
atopile/atopile pull request #21
Opened 2024-01-24 18:29 UTC by mawildoer

2024-01-24 19:17 UTC, napowderly requested changes
Sweet, thanks for cleaning that up!

2024-01-24 19:17 UTC, napowderly commented on src/atopile/cli/build.py
> +        download_footprint(component, footprint_dir=build_args.build_path / "build/footprints/footprints.pretty")
is build path already in /build? I think this should be "footprints/footprints.pretty"

2024-01-24 23:03 UTC, mawildoer commented on src/atopile/config.py
> +    project_context: ProjectContext
Finish moving project-context to that variable

2024-02-01 18:44 UTC, napowderly approved these changes

2024-02-01 18:44 UTC, merged