Picker: Add mechanism to bypass picking container modules
atopile/atopile pull request #565
Opened 2024-11-21 21:05 UTC by sam-mellor

Creates a new `skip_self_pick` trait, used for `MultiCapacitor`, which skips picking for the node itself, but not for any children. Fixes picking a single cap with capacitance equal to the sum of the child caps.

2024-11-23 03:06 UTC, mawildoer approved these changes

2024-11-23 03:06 UTC, mawildoer commented on src/faebryk/libs/picker/picker.py
> +class is_virtual(Module.TraitT):
This should be a `decless` trait
```suggestion
class is_virtual(Module.TraitT.decless()):
```

2024-11-27 15:56 UTC, iopapamanoglou commented
Virtual is a very generic term for what is done here.
How about something like: `force_pick_children`

2024-11-27 15:57 UTC, iopapamanoglou requested changes
See comment

2024-11-29 15:31 UTC, iopapamanoglou commented
`skip_self_pick` is fine

2024-11-29 22:28 UTC, mawildoer approved these changes

2024-11-29 22:28 UTC, mawildoer commented on src/faebryk/libs/picker/picker.py
> +    ...
This isn't required. The doc string is sufficient

2024-11-30 09:12 UTC, iopapamanoglou approved these changes

2024-12-03 06:45 UTC, merged